"""A dropped socket goes back for its shell; a dead one does not.

Phase 91 taught the backend to park a shell for 8 hours after its socket
died. Nothing ever went back for it: the panel set status "closed" and
stopped, so the grace bought nothing a user could see and stepping away
from a laptop ended the session as surely as before.

The panel reconnects now, which turns a close code into behavior. It comes
back from every close EXCEPT the three that mean "there is nothing here",
so this file pins both halves of that bargain:

- a close that carries a final code leaves NOTHING parked (coming back
  would resurrect a shell the user ended, or start a war between tabs), and
- the codes the panel refuses to return from are exactly the ones the
  backend sends.

The last test is the one that earns its place: the two lists live in
different languages and nothing but it connects them.
"""

import re
from pathlib import Path

from app.terminal_sessions import WS_SHELL_GONE, WS_TAKEN_OVER

from tests.test_terminal import launch_connected, read_until
from tests.test_terminal_sessions import FakeWS, make_session


# -- the codes themselves --------------------------------------------------------


def test_the_codes_are_private_range_and_distinct():
    """4000-4999 is the application-private range; anything below it can be
    generated by the browser or the network stack, and a client cannot then
    tell "the shell ended" from "the wifi dropped"."""
    for code in (WS_SHELL_GONE, WS_TAKEN_OVER):
        assert 4000 <= code <= 4999
    assert WS_SHELL_GONE != WS_TAKEN_OVER


# -- unit: the session closes with a reason --------------------------------------


async def test_a_shell_that_exits_says_so_in_the_close_code():
    session, _ = make_session()
    ws = FakeWS()
    await session.attach(ws)
    await session.mark_exited()
    assert ws.closed
    assert ws.close_code == WS_SHELL_GONE
    assert any("shell exited" in t for t in ws.sent)


async def test_a_bare_detach_carries_no_final_code():
    """The complement, and the reason the panel may reconnect at all: when
    the shell is merely parked, nothing tells the client to stay away."""
    session, calls = make_session()
    ws = FakeWS()
    await session.attach(ws)
    session.detach(ws)
    assert not ws.closed                     # server never closed it
    assert ws.close_code is None
    assert calls["closed"] == 0              # and the shell is still running


# -- integration: over a real socket ---------------------------------------------


def test_closing_the_tab_closes_with_gone_and_leaves_nothing_parked(client):
    """The x button. GONE is only honest if the shell is really finished,
    so this asserts the code AND the empty registry behind it."""
    instance_id = launch_connected(client)
    url = f"/instances/{instance_id}/terminal?session=shut"
    with client.websocket_connect(url) as ws:
        read_until(ws, "$ ")
        ws.send_json({"type": "close"})
        assert ws.receive()["code"] == WS_SHELL_GONE
    assert client.app.state.terminal_sessions.get(
        f"inst:{instance_id}:shut") is None


def test_a_stolen_session_tells_the_loser_not_to_fight_for_it(client):
    """Two views on one session id. The first is kicked with TAKEN_OVER;
    without it, the first would reconnect, steal the session back, kick the
    second, and the two tabs would trade the shell forever."""
    instance_id = launch_connected(client)
    url = f"/instances/{instance_id}/terminal?session=contested"
    with client.websocket_connect(url) as first:
        read_until(first, "$ ")
        with client.websocket_connect(url) as second:
            read_until(second, "$ ")
            notice = first.receive_text()
            assert "attached elsewhere" in notice
            assert first.receive()["code"] == WS_TAKEN_OVER


def test_a_dropped_socket_leaves_the_shell_parked_to_come_back_to(client):
    """What the reconnect is FOR. A refresh already proved this path; the
    panel now walks it without one, so it is asserted from the side that
    matters: after the drop, the session is still in the registry."""
    instance_id = launch_connected(client)
    key = f"inst:{instance_id}:parked"
    with client.websocket_connect(
            f"/instances/{instance_id}/terminal?session=parked") as ws:
        read_until(ws, "$ ")
    session = client.app.state.terminal_sessions.get(key)
    assert session is not None
    assert not session.exited
    assert session.detached_at is not None    # parked, waiting for a reattach


# -- the two languages agree -----------------------------------------------------


def test_the_panel_refuses_exactly_the_codes_the_backend_sends():
    """The list lives in TypeScript and the constants live here, so nothing
    but this test connects them. Adding a backend code without adding it
    there means the panel reconnects into a refusal forever; removing one
    there means it gives up on a shell that is still running.

    4403 is the origin/kill-switch refusal in main.py, which has no
    constant of its own because it is the standard "forbidden" spelling
    used by every WS route in the file.
    """
    panel = (Path(__file__).resolve().parents[2]
             / "dashboard" / "components" / "TerminalPanel.tsx").read_text()
    match = re.search(r"const FINAL_CLOSE = \[([0-9,\s]+)\]", panel)
    assert match, "TerminalPanel no longer declares FINAL_CLOSE"
    listed = {int(n) for n in match.group(1).replace(" ", "").split(",") if n}
    assert listed == {4403, WS_TAKEN_OVER, WS_SHELL_GONE}
